language: python

python:
  - "3.6"

install:
  - pip install -r requirements.txt
  - pip install coveralls

script:
  - pytest tests --cov=application --cov-report term-missing


after_success:
  - coveralls
